'''
Hentaibotrip
'''

#configuration
MY_CONSUMER_KEY = 'fip26bAnp2a9KBEJ2OYdSHz0R'
MY_CONSUMER_SECRE= '5utorgXKqdqWMYRreiliJ1Lhppz3CMVMmfikDI4zRWxSutktYx'
MY_ACCESS_TOKEN_KEY = '	894296331984003072-K8Eaif8L6QfcVmWsY780JiUkHkD5i4L'
MY_ACCESS_TOKEN_SECRET = '	oc6gXxbuVrgKR9ZMdUDRm0LGyBkZcMtZ9uSpzYLFgh0Ry'

SOURCE_ACCOUNTS = ["@hentaibongrip"]
ODDS = 8
ORDER = 2
DEBUG = True
STATIC_TEST = False
TEST_SOURCE = ".txt"
TWEET_ACCOUNT = "" 
